swagger: "2.0"
info:
  description: "Api de abertura de conta para o Banco Digital Atnk - Bank."
  version: "1.0.0"
  title: "Abertura de Conta Banco Digital Atnk-Bank"
  contact:
    email: "atnkBanc@bank.com"
  license:
    name: "Apache 2.0"
    url: "http://www.atnkbank.com/"
host: "petstore.swagger.io"
basePath: "/v1"
tags:
  - name: "Abertura de Conta"
    description: "Api de abertura de conta"
schemes:
  - "https"
  - "http"
paths:
  '/cliente':
    post:
      tags:
        - Cliente
      summary: Cadastra Cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente
      parameters:
        - in: body
          name: cliente
          schema:
            $ref: '#/definitions/DadosCadastrais'
      responses:
        201:
          description: Cadastro efetuado com sucesso
        400:
          description: Requisição inválida
        500:
          description: Erro interno no servidor



definitions:
  DadosCadastrais:
    type: object
    properties:
      banco:
        type: integer
        format: int64
        example: 234
      conta-digital:
        type: integer
        format: int64
        example: 2340
      agencia:
        type: string
        example: Janete Silva
      cpf:
        type: string
        minLength: 11
        maxLength: 11
        example: 01234567890

  ClienteResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 234
      titular:
        type: string
        example: Janete Silva
      cpf:
        type: string
        minLength: 11
        maxLength: 11
        example: 01234567890
      senha:
        type: string
        format: password
        example: senha123
      contas:
        type: array
        items:
          $ref: '#/definitions/Conta'

  Conta:
    type: object
    properties:
      agencia:
        type: integer
        format: int32
        example: 975
      numero:
        type: integer
        format: int64
        example: 784563
      digito:
        type: integer
        format: int32
        example: 7
      saldo:
        type: number
        format: double
        example: 101.34
      ClienteResponse:
        $ref: '#/definitions/ClienteResponse'
      transacoes:
        type: array
        items:
          $ref: '#/definitions/Transacao'

  Transacao:
    type: object
    properties:
      id:
        type: integer
        format: int64
      tipo:
        type: string
        enum:
          - debito
          - deposito
      valor:
        type: number
        format: double
      data:
        type: string
        format: date-time
      conta:
        $ref: '#/definitions/Conta'